Demotodo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todos import views
from accounts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todos/',include('todos.urls')),
    url(r'^accounts/',include('accounts.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

todos/urls.py
from django.conf.urls import url
from . import views

app_name = 'todos'

urlpatterns = [
    url(r'^$',views.todos_list,name='list'),
    url(r'^create/$',views.todos_create,name='create'),
    url(r'^about/$',views.todos_about,name='about'),
    url(r'^(?P<id>[\w-]+)/$',views.todos_detail,name='detail'),
    url(r'^update/(?P<id>[\w-]+)/$',views.todos_update,name='update'),
    url(r'^delete/(?P<id>[\w-]+)/$',views.todos_delete,name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models
from django.contrib.auth.models import User
#from django_mysql.models import ListCharField

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.CharField(max_length=500,default=None,null=True)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True,null=True)
    creater = models.ForeignKey(User,default=None,null=True,on_delete=models.CASCADE,)
    #add in author later
    def __str__(self):
        return self.title

todos/forms.py
from django import forms
from . import models

class CreateTodo(forms.ModelForm):
    class Meta:
        model = models.Todo
        fields = ['title','body','slug','thumb']
        

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import  login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('todos:list')
    else:
        form = UserCreationForm(request.POST)
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get())
            else:
                return redirect('todos:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('todos:list')

todos/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Todo
from django.contrib.auth.decorators import login_required
from .forms import CreateTodo

# Create your views here.
# To display all lists of todos
@login_required(login_url='/accounts/login/')
def todos_list(request):
    todos = Todo.objects.all().filter(creater = request.user).order_by('date')
    return render(request,'todos/todos_list.html',{'todos':todos})


# To create new todo
@login_required(login_url='/accounts/login/')
def todos_create(request):
    if request.method == 'POST':
        todos = CreateTodo(request.POST,request.FILES)
        if todos.is_valid():
            #save article to db 
            instance = todos.save(commit=False)
            instance.creater = request.user
            instance.save()
            return redirect('todos:list')
    else:
        todos = CreateTodo()
    return render(request,'todos/todos_create.html',{'todos':todos})

# To display details of todo
@login_required(login_url='/accounts/login/')
def todos_detail(request,id):
    todos = Todo.objects.get(id=id)
    return render(request,'todos/todos_detail.html',{'todos':todos})

def todos_about(request):
    return render(request,'todos/about.html')

#To Update existing todo
@login_required(login_url='/accounts/login/')
def todos_update(request,id):
   # print(t)
    todos = Todo.objects.get(id=id)
    form = CreateTodo(request.POST,request.FILES,instance=todos)
    if form.is_valid():
        form.save()
        return redirect('todos:list')

    return render(request,'todos/todos_update.html',{'form':form, 'todos':todos})

# To Delete existing todos
def todos_delete(request,id):
    todos = Todo.objects.get(id=id)
    if request.method == 'POST':
        todos.delete()    
        return redirect('todos:list')

    return render(request,'todos/todos_delete.html',{'todos':todos})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <form action="{% url 'accounts:login' %}" class="site-form" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" value="{ request.GET.next }" name="next">
    {% endif %}
    <input type="submit" value="Login">
    </form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Please Register here</h1>
<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base Layout</title>
    <!-- Bootstrap links -->
    <!-- Latest compiled and minified CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Css file-->
    <link rel="stylesheet" href="/assets/style.css">
</head>
<body>

    <div class="wrapper">
           
        <h1><a href="{% url 'todos:list' %}"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <nav class="navbar navbar-inverse">
                        <div class="container-fluid">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'todos:list' %}">TODOS</a>
                          </div>
                          <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url 'todos:create'%}">New</a></li>
                            <li><a href="{% url 'todos:about'%}">About</a></li>
                            <li>
                               <form action="{% url 'accounts:logout' %}" class="logout-link" method="POST">
                                {% csrf_token %}<button type="submit"> <p></p> <p></p> Logout</button>
                                    </form>
                                </li>

                          </ul>
                        </div>
                      </nav>

                      <p>welcome {{ user.username }}</p>
               
                
                {% else %}
                     <nav class="navbar navbar-inverse">
                        <div class="container-fluid">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'todos:list' %}">TODOS</a>
                          </div>
                          <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url 'todos:create'%}">New</a></li>
                            <li><a href="{% url 'todos:about'%}">About</a></li>
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a href="{% url 'accounts:signup' %}    ">Signup</a></li>
                          </ul>
                        </div>
                      </nav>
              
                {% endif %}
                
            </ul>
        </nav>
    {% block content %}
    {% endblock %}
    </div>

</body>
</html>

todos/templates/todos/about.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static from staticfiles %}
<div class="container">
  <h1>About us </h1>
  <p>
        To Do lists, from helping you prioritize your time to helping you remember what it is you meant to do! For us, to do lists are absolutely invaluable. It’s a very simple strategy that works great!
        All the best..! Go prepare your Todo List 
  </p>
</div>
{% endblock %}

todos/templates/todos/todos_create.html
{% extends "base_layout.html" %}

{% block content %}
<div class="create_todos">
    <h2>Create an Awesome New Todo list </h2>
    <form  class="site-form" action="{% url 'todos:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ todos }}
        <input type="submit" value="Create">
    </form>

</div>
<!--<script src="/static/slugify.js"></script>-->
{% endblock %}

todos/templates/todos/todos_delete.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Delete Todo</h1>
    
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete {{ todos.title}}</h2>
        <button type="submit">Delete</button>
    </form>

{% endblock %}

todos/templates/todos/todos_detail.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static from staticfiles %}
<div class="detail_todos">
  <div class="todo">
    
     <h2><a href="{% url 'todos:update' todos.id %}">update TODO</a></h2>
        <h3>{{ todos.title }}</h3>    
  <!-- <img src="{% static 'one.jpeg' %}" alt="img not found">-->
    <p>{{ todos.body }}</p>
    <p>{{ todos.date }}</p>
    <p class="creater">Added by {{ todos.creater.username}}</p>
</div>
</div>
{% endblock %}

todos/templates/todos/todos_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Todo List</h1>

    <div class="todos">
        {% for todo in todos %}
        <div class="todo">
            <h2><a href="{% url 'todos:detail' todo.id %}">{{ todo.title}}</a></h2>
            <h3>{{ todo.title }}</h3>
            <p>{{ todo.body }}</p>
            <p>{{ todo.date }}</p>
            <p class="creater">Added by {{ todo.creater.username }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

todos/templates/todos/todos_update.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>New/Update Todo</h1>
    
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <p>
        <button class="btn btn-primary" type="submit">Save</button></p>
    </form>

    {% if todos %}
    <h3><a href="{% url 'todos:delete' todos.id %}">Delete TODO</a></h3>
    {% endif %}
{% endblock %}